diff_drive_controller:
  type: "diff_drive_controller/DiffDriveController"
  left_wheel: "front_left_wheel_joint"
  right_wheel: "front_right_wheel_joint"
  wheel_separation: 0.58306      # distance between left and right wheels (0.29153 * 2)
  wheel_radius: 0.16459          # radius of your wheels from URDF
  cmd_vel_timeout: 0.5
  velocity_rolling_window_size: 2
  enable_odom_tf: true
  odom_frame: "odom"
  base_frame: "base_link"
  publish_rate: 50
  pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.0, 0.0, 0.0]
  twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.0, 0.0, 0.0]
